//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanHafner.GooKit.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JanHafner.GooKit.Services.Properties.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access code could not be retrieved..
        /// </summary>
        internal static string AccessCodeCouldNotBeRetrievedExceptionMessage {
            get {
                return ResourceManager.GetString("AccessCodeCouldNotBeRetrievedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either an api key or OAuth 2 authorization must be provided..
        /// </summary>
        internal static string ApiKeyAndOAuth2NotProvided {
            get {
                return ResourceManager.GetString("ApiKeyAndOAuth2NotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string JWTAlgorithmNotSupportedExceptionMessage {
            get {
                return ResourceManager.GetString("JWTAlgorithmNotSupportedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Base64 string &apos;{0}&apos; was detected as illegal..
        /// </summary>
        internal static string JWTIllegalBase64StringExceptionMessage {
            get {
                return ResourceManager.GetString("JWTIllegalBase64StringExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature &apos;{0}&apos; is invalid because expected was &apos;{1}&apos;..
        /// </summary>
        internal static string JWTInvalidSignatureExceptionMessage {
            get {
                return ResourceManager.GetString("JWTInvalidSignatureExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request needs to be authorized but the authorization context has not handled the authorization process..
        /// </summary>
        internal static string RequestNeedsAuthorization {
            get {
                return ResourceManager.GetString("RequestNeedsAuthorization", resourceCulture);
            }
        }
    }
}
